# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experiment3.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='experiment3.proto',
  package='Experiment3Data',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x65xperiment3.proto\x12\x0f\x45xperiment3Data\"\xc6\x01\n\x10\x45xperiment3_prop\x12\x0c\n\x04nome\x18\x01 \x02(\t\x12\x0e\n\x06pk_uid\x18\x02 \x02(\x05\x12\r\n\x05ucs19\x18\x03 \x02(\t\x12\r\n\x05\x63\x31_19\x18\x05 \x02(\t\x12\r\n\x05\x63\x32_19\x18\x06 \x02(\t\x12\r\n\x05\x63\x33_19\x18\x07 \x02(\t\x12\x0f\n\x07regione\x18\x08 \x02(\t\x12\x11\n\tsiglaprov\x18\t \x02(\t\x12\x10\n\x08siglareg\x18\n \x02(\t\x12\x10\n\x08\x63odistat\x18\x0b \x02(\t\x12\x10\n\x08geometry\x18\x0c \x02(\t\"M\n\x13\x45xperiment3Polygons\x12\x36\n\x0b\x65xperiment3\x18\x01 \x03(\x0b\x32!.Experiment3Data.Experiment3_prop'
)




_EXPERIMENT3_PROP = _descriptor.Descriptor(
  name='Experiment3_prop',
  full_name='Experiment3Data.Experiment3_prop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='Experiment3Data.Experiment3_prop.nome', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pk_uid', full_name='Experiment3Data.Experiment3_prop.pk_uid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ucs19', full_name='Experiment3Data.Experiment3_prop.ucs19', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c1_19', full_name='Experiment3Data.Experiment3_prop.c1_19', index=3,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c2_19', full_name='Experiment3Data.Experiment3_prop.c2_19', index=4,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c3_19', full_name='Experiment3Data.Experiment3_prop.c3_19', index=5,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regione', full_name='Experiment3Data.Experiment3_prop.regione', index=6,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='siglaprov', full_name='Experiment3Data.Experiment3_prop.siglaprov', index=7,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='siglareg', full_name='Experiment3Data.Experiment3_prop.siglareg', index=8,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codistat', full_name='Experiment3Data.Experiment3_prop.codistat', index=9,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='Experiment3Data.Experiment3_prop.geometry', index=10,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=237,
)


_EXPERIMENT3POLYGONS = _descriptor.Descriptor(
  name='Experiment3Polygons',
  full_name='Experiment3Data.Experiment3Polygons',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='experiment3', full_name='Experiment3Data.Experiment3Polygons.experiment3', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=316,
)

_EXPERIMENT3POLYGONS.fields_by_name['experiment3'].message_type = _EXPERIMENT3_PROP
DESCRIPTOR.message_types_by_name['Experiment3_prop'] = _EXPERIMENT3_PROP
DESCRIPTOR.message_types_by_name['Experiment3Polygons'] = _EXPERIMENT3POLYGONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Experiment3_prop = _reflection.GeneratedProtocolMessageType('Experiment3_prop', (_message.Message,), {
  'DESCRIPTOR' : _EXPERIMENT3_PROP,
  '__module__' : 'experiment3_pb2'
  # @@protoc_insertion_point(class_scope:Experiment3Data.Experiment3_prop)
  })
_sym_db.RegisterMessage(Experiment3_prop)

Experiment3Polygons = _reflection.GeneratedProtocolMessageType('Experiment3Polygons', (_message.Message,), {
  'DESCRIPTOR' : _EXPERIMENT3POLYGONS,
  '__module__' : 'experiment3_pb2'
  # @@protoc_insertion_point(class_scope:Experiment3Data.Experiment3Polygons)
  })
_sym_db.RegisterMessage(Experiment3Polygons)


# @@protoc_insertion_point(module_scope)
